// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zhalvnujwcvcdhmezytw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpoYWx2bnVqd2N2Y2RobWV6eXR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4OTA3OTEsImV4cCI6MjA3MDQ2Njc5MX0.YebL3Urn2x6EECvCOxijbJcj8wM4BlnvwxWnDQG4zr4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});